### ISSUE TITLE
Disroot no longer supports 2fa on Email, only Cloud

### ISSUE THREAD

**Issue by Dyrimon** [privacyguides/privacyguides.org#1075]
## Description
Disroot has disabled their 2fa on email when they switched from rainloop to SnappyMail

**URL of affected page:**
https://www.privacyguides.org/email/#disroot

The affected page declares Disroot supports TOTP 2fa on email, but it's no longer true. As a disroot user myself, I've noticed this when I bypassed 2fa on login. The [FAQ page](https://disroot.org/en/faq) on 2fa says that now it only supports 2fa on cloud. https://howto.disroot.org/en/tutorials/cloud/settings#two-factor-authentication

And this change does not meet the minimum to qualify criteria for Email category according to the PG criteria.

**Comment by jonaharagon** [comment]
@dngray can you check this?

**Comment by darhma** [comment]
The 2fa on email with IMAP/SMTP does not make much sense as explained here: https://github.com/the-djmaze/snappymail/issues/84#issuecomment-817852617

**Comment by dngray** [comment]
Ill check with them to see if this is temporary, or if they're planning to support that.

**Comment by jonaharagon** [comment]
> The 2fa on email with IMAP/SMTP does not make much sense

The benefit of it is that webmail often has account management functionality in addition to just email capabilities. If you can do things like change your password via webmail, for example, 2FA does still provide benefit.

**Comment by muppeth** [comment]
We have decided to remove 2FA on webmail during the switch to snappymail yesterday because it was causing confusion for people (verification code field was ever present during login even for those not using 2FA which caused ton of questions). This was also good opportunity to remove it because it only created illusion of security for people since you could just use IMAP to circumvent it. We have enabled it because of the pressure of some users in the past and I think it was a mistake to do it. 
That said, we want to actually work on service wide 2FA solution to provide truly two factor solution for the entire platform. 

https://disroot.org/en/blog/2022-04-snappymail

**Comment by darhma** [comment]
> The benefit of it is that webmail often has account management functionality in addition to just email capabilities. If you can do things like change your password via webmail, for example, 2FA does still provide benefit.

I use disroot as my mail provider and in the new webmail interface there doesn't seem to be an option to change the password.

**Comment by Dyrimon** [comment]
> I use disroot as my mail provider and in the new webmail interface there doesn't seem to be an option to change the password.

Indeed, I just noticed that the only security functions in the "Security" section of the webmail is PGP related only.

**Comment by Dyrimon** [comment]
@muppeth I do not think SnappyMail will be ideal for Disroot, when it's missing important features like MFA, changing password and deleting account.

**Comment by dngray** [comment]
Even providers like mailbox.org use a "[services password](https://kb.mailbox.org/en/private/account-article/how-to-use-two-factor-authentication-2fa)". With that "services password" you can [reset your main password](https://login.mailbox.org/en/passwordrecovery) which sends an email to your inbox, so although Mailbox.org supports 2FA it's really still limited to that "services password". If we compare this to Google's "[less secure password](https://support.google.com/accounts/answer/6010255)" by comparison, you can't hijack a Google account with that and reset the main password.

If we did enforce this requirement in respect to Disroot, we'd really need to look at other providers too.

I wish everything supported FIDO2/WebAuthn, because the anti phishing capabilities of platform authentication and security keys beat everything else hands down, sadly though privacy providers (even ProtonMail) are dragging their boots with this.

**Comment by subatomic-honda-civic** [comment]
> > The benefit of it is that webmail often has account management functionality in addition to just email capabilities. If you can do things like change your password via webmail, for example, 2FA does still provide benefit.
> 
> I use disroot as my mail provider and in the new webmail interface there doesn't seem to be an option to change the password.

@darhma AFAIK, there was no option from the start, you would have to login into the main site (https://user.disroot.org) and change it from there.
