### ISSUE TITLE
Missing git submodule (mkdocs-material-insiders)

### ISSUE THREAD

**Issue by sfermigier** [privacyguides/privacyguides.org#1183]
Here's what I get when trying to clone the repo:

```
$ git clone --recurse-submodules https://github.com/privacyguides/privacyguides.org
Cloning into 'privacyguides.org'...
remote: Enumerating objects: 16207, done.
remote: Counting objects: 100% (553/553), done.
remote: Compressing objects: 100% (296/296), done.
remote: Total 16207 (delta 268), reused 504 (delta 237), pack-reused 15654
Receiving objects: 100% (16207/16207), 37.09 MiB | 9.92 MiB/s, done.
Resolving deltas: 100% (9809/9809), done.
Submodule 'mkdocs-material-insiders' (git@github.com:privacyguides/mkdocs-material-insiders.git) registered for path 'mkdocs-material'
Cloning into 'zzz/privacyguides.org/mkdocs-material'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

**Comment by subatomic-honda-civic** [comment]
Seems that something happened to https://github.com/privacyguides/mkdocs-material-insiders that made it just decided to not exist.

**Comment by lx-is** [comment]
@subatomic-honda-civic PrivacyGuides [sponsors](https://github.com/orgs/privacyguides/sponsoring) MkDocs Material for access to the Insiders program, and, as such, they get access to pre-release versions with a plethora of extra features. For obvious reasons, the paid repository can only be accessed by team members.

The repository [uses](https://github.com/privacyguides/privacyguides.org/commit/d1f9813c3bfca68607701586d688bf13183da82d) PG's own fork of the insider build, which is why the PG insider repo is the one privated and not the generic insider repository.
