### ISSUE TITLE
Are you secretly paid by red hat

### ISSUE THREAD

**Issue by atoxique** [privacyguides/privacyguides.org#1252]
## Description

there is no other website out there that promotes fedora and other red hat technologies like wayland as hard as this website does. also you lie about debian claiming it's less private/secure because it bases on older packages, despite the fact debian has one of the most proactive security teams out there actively backporting fixes to these older package versions even without a CVE which you lie is necessary. there's a reason debian is used so much in production and servers. "We don’t believe holding packages back and applying interim patches is a good idea, as it diverges from the way the developer might have intended the software to work" is some of the biggest bullsh*t i've ever heard. btw let's not forget when fedora left everyone vulnerable when they refused to roll out firefox 97.0.2 which fixed a 0day exploit and instead waited for firefox 98. who's insecure now ;)

**URL of affected page:**

https://www.privacyguides.org/linux-desktop/
https://www.privacyguides.org/linux-desktop/overview/

**Comment by mfwmyfacewhen** [comment]
Yes

**Comment by blacklight447** [comment]
Let me just give you this link: https://opencollective.com/privacyguides

Here you can see exactly who donated to us and where the money is going.

Further more, no, we are not paid by redhat.

**Comment by mfwmyfacewhen** [comment]
Joking aside, make a [discussion](https://github.com/privacyguides/privacyguides.org/discussions) if you want to discuss the recommendations, but please leave the conspiracy theories at the door.

**Comment by tommytran732** [comment]
I have been exposed 🤡

**Comment by dngray** [comment]
> red hat technologies like wayland

Wayland isn't exclusive to Redhat. Besides X11 being insecure, [nobody really wants to maintain it](https://www.phoronix.com/scan.php?page=news_item&px=X.Org-Maintenance-Mode-Quickly).

> debian claiming it's less private/secure because it bases on older packages, despite the fact debian has one of the most proactive security teams

They act on CVEs. As the repository is huge, there are plenty of vulnerabilities which don't get a CVE and aren't on their radar.

> actively backporting fixes to these older package versions even without a CVE which you lie is necessary

Just because they do sometimes, doesn't mean they do most of the time.

> there's a reason debian is used so much in production and servers

That's not the reason, it's because it's a very bare bones distribution that has been around a long time. These days though you're more likely to see Ubuntu and Centos servers.

Finally the page there is a Linux desktop page recommendation list, and Debian Stable makes a pretty uncomfortable desktop distribution, unless you like really ancient software with bugs and annoyances frozen in there until the next release.

> fedora left everyone vulnerable when they refused to roll out firefox 97.0.2 which fixed a 0day exploit and instead waited for firefox 98

That release came out fairly quick succession. Debian only ships ESR.

> "We don’t believe holding packages back and applying interim patches is a good idea, as it diverges from the way the developer might have intended the software to work" is some of the biggest bullsh*t i've ever heard

It's not bullshit, it means it lacks the QA of upstream testing. Sometimes more than one thing changes in between releases of a library.

You might also like to read this about [unstable](https://www.debian.org/security/faq#unstable) and [testing](https://www.debian.org/security/faq#testing) in case you were thinking of suggesting Debian Testing.

**Comment by Zanthed** [comment]
Debian is known to ignore backporting CVEs by using their "DSAs" (Debian Security Advisories which are "CVE compatible") and picking and choosing which CVEs they want to backport or not. They do this with Chromium and the Linux kernel already. Their DSAs are not at all a reflection of the known CVEs out there.
