### ISSUE TITLE
Prefer DNS over extensions for content blocking

### ISSUE THREAD

**Issue by peewoper** [privacyguides/privacyguides.org#1335]
## Description
DNS content blocking should be preferred over extensions, because of the security benefits.
That should be made clear.

**URL of affected page:**
https://www.privacyguides.org/browsers/#additional-resources

**Comment by dngray** [comment]
> DNS content blocking should be preferred over extensions, because of the security benefits.

They do provide different feature sets. DNS based blocking is useless against first party script blocking or actually modifying the document object model of a page so there are trade offs.

When you DNS block you'll get a "white square" instead of no advertisement at all.

If you use the default lists you should be okay.
