### ISSUE TITLE
Place A Warning For DDG

### ISSUE THREAD

**Issue by ProfessorCode212** [privacyguides/privacyguides.org#1356]
Given [what happened recently](https://techcrunch.com/2022/05/24/ddg-microsoft-tracking-blocking-limit/), I think it would be a good idea to place a warning for _DuckDuckGo_. Although this is related to their web browser and not the search engine, it is important to inform users of this. It would also be ideal if _DuckDuckGo_ can be placed **further down the page**.

Affected URL: https://www.privacyguides.org/search-engines/

**Comment by dngray** [comment]
> Although this is related to their web browser and not the search engine, it is important to inform users of this.

We don't don't recommend their browser, as there is no real good reasons to use it. I'm not sure where such a warning would go.

> It would also be ideal if _DuckDuckGo_ can be placed **further down the page**.

Reluctant to do this, as it's one of the only search engines that has a .onion entrance, and also there is no third party scripts running on duckduckgo.com

**Comment by jonaharagon** [comment]
I don't think we should get into excessive warnings or ordering recommendations by some arbitrary priority like this. Either something is good enough to be recommended or it isn't, at the end of the day. Since we only recommend DuckDuckGo's search product, which is unaffected by any of this, it doesn't really make sense to change anything to me.

Even in the context of their browser, I don't really see how this reveal changes anything for its users either. The DDG browser is still protecting them from the privacy threats it is designed to protect against. It doesn't provide total anonymity online, just like Firefox or even Brave Brave with Tor mode enabled wouldn't. People who are realistically concerned about this kind of thing should be using Tor Browser.

**Comment by RustoMCSpit** [comment]
Can we have a re-review after a year?

**Comment by jonaharagon** [comment]
Has something changed in the last year that invalidates our discussion?

The best place to talk about DuckDuckGo is on https://discuss.privacyguides.org unless something we say about it on the website currently is objectively incorrect.
