### ISSUE TITLE
Refinements to website redesign

### ISSUE THREAD

**Issue by ghost** [privacyguides/privacyguides.org#1362]
Tracker for some after the fact improvements to #1360 

<div type='discussions-op-text'>

- [ ] Dark mode homepage should use a minor gradient to match the header color towards the top
- [x] Change the text selection highlight color to match the branding
- [ ] Redesign the code blocks to match the new themes
- [x] Add margin to homepage buttons for mobile
- [x] Move blog RSS icon to footer
- [x] Preload header font to fix pop-in (#1367)
- [x] Redesign left side scroll bar (rounded and maybe diff colors)
- [ ] Fade left side navigation when cutoff `0 0 .4rem .4rem var(--md-default-bg-color)`
- [ ] Update mobile navigation chevron
- [ ] Update mobile navigation back arrow
- [ ] Fix toggle-able admonition border radius on hover
- [ ] Center annotation `+` icon
- [ ] Fix blog centering when blog list is hidden (i.e. in tor browser default window size)
- [ ] Decrease minimum screen size for mobile view (so at least tor browser default size has the standard layout)

</div>

**Comment by noClaps** [comment]
You should animate the dropdown for the Downloads menus. It looks a lot better. Here's my implementation: https://codeberg.org/tcgmoo/pages/src/branch/main/docs/assets/javascripts/accordion.js

The `<details>` element works without js anyway, so any visitors to the site not using js won't be losing any functionality. The script simply animates the dropdown for those with js enabled.

**Comment by 3Kevi** [comment]
I think, according to UX design principles you should change "Switch to light/dark mode" buttons the other way around. Because when you want to press a button, you show your intention to change the colour scheme to your desired one.

![image](https://user-images.githubusercontent.com/82259360/171133307-cfa42251-0738-4d66-ab1a-53a9413f7d87.png)
![image](https://user-images.githubusercontent.com/82259360/171133490-c50fc3c3-dab9-42ef-bed0-360d4ec90ef5.png)

**Comment by jonaharagon** [comment]
There's hardly a consensus out there, but most sources indicate that displaying the _current_ state is the best way to handle toggles like this.

We could look into displaying the opposite icon on hover, maybe?

**Comment by noClaps** [comment]
I don't think having either way is wrong. I personally use the method they suggest on my own website, but you could make arguments for either method.

I like the animated style Google did on https://fonts.google.com/ but I couldn't figure out how to implement it myself. Maybe something similar could be used if you could figure it out?

**Comment by 27lx** [comment]
> I think, according to UX design principles you should change "Switch to light/dark mode" buttons the other way around. Because when you press a button, you show your intention to change the colour scheme to your **desired** one.

The way it currently is seems to be the most standard approach, which I would argue is the right way to do it aesthetically.

Some notable examples of other sites that show a sun icon in light mode and vice versa are:
- [Tailwind CSS](https://tailwindcss.com/docs/installation)
- [1Password](https://1password.com/mac/)
- [Replit](https://docs.replit.com/)

etc

> We could look into displaying the opposite icon on hover, maybe?

Could be cool, if even possible. It would be hard to execute a good looking animation though, because a transition on its own probably wouldn't be ideal. Maybe a little _pop_ effect when hovering, where the sun rays move away from the center slightly and the star in the moon icon moves away a bit. idk

**Comment by jonaharagon** [comment]
This is a native feature https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=back+to+top#back-to-top-button

**Comment by 27lx** [comment]
> The list of downloads should have a standard order.

Yeah, it could definitely use some standardization. Bit outside the scope of the redesign though, since it's really just CSS edits that don't conflict with any page content. Could be helpful to have the order detailed in the style guide.

**Comment by mfwmyfacewhen** [comment]
> The list of downloads should have a standard order.

This would make a good discussion.

**Comment by noClaps** [comment]
Links should be underlined on hover. Right now it's not easy to tell if I've selected a link or not, especially on a low-contrast display.

Also, links that have been opened should have a different color to the other regular links.

**Comment by jonaharagon** [comment]
Closing because I believe this issue is out of date.
