### ISSUE TITLE
Remove OpenSUSE or warn users against Packman

### ISSUE THREAD

**Issue by matchboxbananasynergy** [privacyguides/privacyguides.org#1446]
This is from @martin0x72:matrix.org in the Matrix Privacy Guides room. I am merely copying and pasting from there for them.

"I would like to suggest a change in the guide.

OpenSUSE Tumbleweed is recommended as a distribution for people who want to install GNU/Linux (https://www.privacyguides.org/linux-desktop/#opensuse-tumbleweed).

However, there is a problem with it, it does not contain patented codecs by default. It requires you to add a 3rd party repository called Packman
(https://en.opensuse.org/SDB:Installing_codecs_from_Packman_repositories).

Because you quote Richard Brown here: https://www.privacyguides.org/linux-desktop/overview/#release-cycle, I think you should also read his opinion about Packman: https://old.reddit.com/r/openSUSE/comments/nllou9/security_updates_in_packman_and_other_obs_repos/gzm4bol/"

**URL of affected page:**
https://www.privacyguides.org/linux-desktop/#opensuse-tumbleweed

**Comment by tommytran732** [comment]
Not gonna do this, because it is the same with Fedora and RPMFusion. This is a legal issue, not a technical one, and neither of them could solve it until tue patent expires without putting millions of dollars into it. One viable alternative to this is to use Flathub.

I would be in favor of removing both distros if it was some ideological non-sense, but it's not, so we can't really fault them for it.
