### ISSUE TITLE
Bitlocker section is missing important information

### ISSUE THREAD

**Issue by Batcherdink** [privacyguides/privacyguides.org#1493]
## Description

Please see:

- https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-countermeasures
- https://dolosgroup.io/blog/2021/7/9/from-stolen-laptop-to-inside-the-company-network

Just enabling bitlocker is not enough as it is insecure by default

https://www.privacyguides.org/encryption/#bitlocker

**Comment by dngray** [comment]
This doesn't really prove anything. Such an attack needs the owner, to present credentials thus highly targeted in order to capture any secrets over SPI. In such scenario an adversary could just use a more physical and "direct" approach to your person instead, thereby bypassing the need to any electronics equipment. For such scenarios, the only recommendation would be that such sensitive data, access should not be possible outside the physical building where it is located, and that is not the aim of Privacy Guides.
