### ISSUE TITLE
VPN no log policy

### ISSUE THREAD

**Issue by Lostname777** [privacyguides/privacyguides.org#1498]
Description: All the three VPN have gone no-log policy audit now but you haven't changed this danger icon:

"It is important to note that using a VPN provider will not make you anonymous, but it will give you better privacy in certain situations. A VPN is not a tool for illegal activities. **Don't rely on a "no log" policy**."

URL of affected page: https://www.privacyguides.org/vpn/#our-criteria

**Comment by TrashPandaCodingGarbage** [comment]
I think it still count, as a VPN provider potentially could change their server settings after no log audit have been performed to turn on the logging.

**Comment by Lostname777** [comment]
I see

**Comment by Zanthed** [comment]
You can't verify they aren't actually logging. The warning still applies. You are always trusting the VPN provider's words.

**Comment by Lostname777** [comment]
Then what does it i mean to audit? If that's the case then company can remove a backdoor and do audit and then add it again. Then the whole point of no-log audit useless?

**Comment by jonaharagon** [comment]
Audits aren't a technical guarantee, they are just another factor to consider when evaluating the provider's trustworthiness. Audits also provide a guarantee of technical _competence_. If a provider is storing your logs when they claim not to, it's either because they are actively malicious, or they have incompetently misconfigured their servers. Audits proving their servers say what they do eliminates the latter possibility. There are many ways an _actively malicious_ VPN provider can harm its users, which is why it is important to understand that VPNs can never provide any semblance of anonymity, and you cannot rely on the companies policies alone, so the warning remains important.
