### ISSUE TITLE
Broken question mark/explanation when hovering over words on DNS page.

### ISSUE THREAD

**Issue by TheW0LVERIN3** [privacyguides/privacyguides.org#1510]
## Description
On the DNS Resolvers page under Recommendations, when hovering over DNS or ECS the question mark appears but the explanation appears on the top left, half readable. I assume this is not intended behavior.

![image](https://user-images.githubusercontent.com/44342613/177194019-b3b79869-dc08-41bb-adf9-ab3c01c09a84.png)

**Comment by jonaharagon** [comment]
I'm closing this issue, as it's an upstream issue I'm not interested in fixing here. I reported this to the mkdocs-material issue tracker (linked above) and gave a few suggestions on how this might be fixed there. If this is fixed in mkdocs-material or someone wants to create a PR in our repo fixing it, I will merge a fix 👍
