### ISSUE TITLE
Note Mailbox.org's weak TOTP implementation

### ISSUE THREAD

**Issue by Gunther0042** [privacyguides/privacyguides.org#1596]
## Description

One of the minimum requirements for an email service to qualify as recommended is "Protection of webmail with 2FA, such as TOTP." While Mailbox.org *technically* fulfills this requirement, its TOTP implementation weakens the the first factor (the password). TOTP only works when the password is changed to a 6-digit numeric PIN. The TOTP code is then appended to the PIN by the user and entered into the password field when logging in to the webmail (a standard password is still used for IMAP clients). This is obviously a subpar TOTP implementation since it significantly weakens the first factor by limiting it to 6 numeric characters. I recently tried out Mailbox.org for myself and was very surprised to see TOTP implemented this way.

Mailbox.org's TOTP implementaion is described in their documentation [here](https://kb.mailbox.org/en/private/account-article/how-to-use-two-factor-authentication-2fa), but is discussed more in-depth in this forum post [here](https://userforum-en.mailbox.org/topic/lets-talk-about-2fa-on-this-website-again). Mailbox.org responds to the complaint by saying that since the account password is stored in IMAP clients in plaintext having a distinct PIN for the webmail is superior and that the advantage of OTP outweighs the loss of complexity in the password. But it's unclear why the webmail password is restricted to six numeric digits at all. They do say they want to implement more ways to use OTP in the future, but the forum post is a few years old and they have not yet changed anything.

Mailbox.org still offers Yubikey support for the second factor but I think their weak TOTP implementation is worth at least mentioning alongside the recommendation. While I wouldn't call the current description inaccurate, I would call it misleading since it may lead readers to expect a level of security from the service that they will not actually receive. 

**URL of affected page:https://www.privacyguides.org/email/#mailboxorg**

**Comment by jonaharagon** [comment]
Note for our PR: It's actually a **4-digit alphanumeric PIN**, not a 6-digit numeric PIN.

This is actually a very strange implementation, and I'm struggling to figure out why they chose to do it this way. I do believe this is still significantly more secure than a strong single-factor login though, so we should still recommend using 2FA, and this method in fact is a better solution than what some previously recommended providers (Disroot) implemented.

One thing that confuses me is how this works with IMAP/non-webmail clients from a technical perspective. Imagine my personal PIN is ABCD and the first time I sign in to an IMAP client the OTP code I use is 123456. Presumably I log in with ABCD123456, and Mailbox.org will allow my IMAP client to continue accessing my email after the first successful sign-in, so I don't have to type in a new password every time I check my email. But how does Mailbox.org allow my IMAP client to continue using ABCD123456 as a password even after my OTP code has changed? Does it identify my IMAP client in some other manner somehow, or does it save ABCD123456 as an acceptable password for my IMAP client to use in some database, so that it remains valid after an OTP code change?

If it's the latter, would I be able to use ABCD123456 on a second IMAP client well after my OTP code changes, because that specific combination is considered acceptable in order for my first IMAP client to connect? If so, that would be a significant security flaw, reducing my account security from a 4-character PIN + constantly changing OTP to a mere 10-character PIN, because some combinations remain static.

I'm assuming/hoping this is **not** how this works, but I do want to test this possibility anyhow just in case.

**Comment by dngray** [comment]
There are a few things here which are a bit out of proportion.

> TOTP only works when the password is changed to a 6-digit numeric PIN. The TOTP code is then appended to the PIN by the user and entered into the password field when logging in to the webmail (a standard password is still used for IMAP clients).

> This is obviously a subpar TOTP implementation since it significantly weakens the first factor by limiting it to 6 numeric characters. I recently tried out Mailbox.org for myself and was very surprised to see TOTP implemented this way.

It is a 4 digit code, but it doesn't really matter because at that point you've added sufficient entropy to the password. Note that code can be (any 4 numbers, symbols, or letters, with or without mixed case).

When you've entered that and the TOTP code, or the Yubico OTP code (which is the stronger option), the authentication token has sufficient entropy and also meets necessary "something you know, and something you have".

Realistically at this point having a stronger PIN (that is longer than 4 digits) is not going to make the final token any stronger.

> Mailbox.org responds to the complaint by saying that since the account password is stored in IMAP clients in plaintext having a distinct PIN for the webmail is superior and that the advantage of OTP outweighs the loss of complexity in the password. But it's unclear why the webmail password is restricted to six numeric digits at all. They do say they want to implement more ways to use OTP in the future, but the forum post is a few years old and they have not yet changed anything.

The most secure way for a provider presently to set this up is to use the [OAuth protocol](https://en.wikipedia.org/wiki/OAuth) when authenticating via IMAP. IMAP does in fact allow this, and the most popular method is `SASL XOAUTH2` which [Google](https://developers.google.com/gmail/imap/xoauth2-protocol#imap_protocol_exchange), [Microsoft](https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth) and [Yahoo](https://senders.yahooinc.com/developer/documentation/) offer. Clients which support this modern authentication protocol, will then show a contextually limited browser window which even allows [FIDO2/WebAuthn](https://www.privacyguides.org/basics/multi-factor-authentication/#fido-fast-identity-online), meaning you don't actually need a password at all.

With the [autoconfiguration format](https://wiki.mozilla.org/Thunderbird:Autoconfiguration) you can add DNS [TXT records](https://wiki.mozilla.org/Thunderbird:Autoconfiguration:DNSBasedLookup) which point to the login page. It can even work for custom domains if you [add the record](https://kb.mailbox.org/en/private/e-mail-article/using-e-mail-addresses-of-your-domain#Usingemailaddressesofyourdomain-Optional:Howtoenableauto-configurationine-mailclients).

It's worth noting that Mailbox.org has some security benefits over Proton Mail, and even Tutanota, for example you can encrypt all incoming email with a public key, and not even supply the private key to Mailbox.org. This in theory would mean it would be impossible for them to serve you version of the web app that steals your private key passphrase. One could argue on that basis mailbox.org could be more secure than alternatives.

> I'm actually even more confused, because at a second look 2FA is actually not available for IMAP devices at all.

You can still use a services password any length you want. Mine is 79 characters long, is encrypted with my PGP key, and requires my Yubikey to decrypt.

Anyway I'm going to close this because it's not really "that weak". If we want to make a PR on this we could state that you can:

- Improve security by not using TOTP, and instead use [Yubico OTP](https://www.privacyguides.org/basics/multi-factor-authentication/#yubico-otp).
- Set a long "services" password, and don't login to other people's devices with it

With mobile phone security it is quite difficult to steal the "services password" from applications without significant effort anyway. Of course it does go without saying rooting your phone does make it easier for an attacker to some extent.
