### ISSUE TITLE
macOS related guide

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#1858]
## Description

**URL of affected page:** Like we have a Linux page currently, and are looking at a Windows page, we should have a macOS page.

This issue will serve as some draft notes for that page.

I want to move the filevault section from the encryption page to this page. We should also have a reminder there about backing up the master key to iCloud. This may not be appropriate for users and they should consider carefully.

**Comment by freddy-m** [comment]
Would be interested to hear your thoughts on this @mfwmyfacewhen

**Comment by mfwmyfacewhen** [comment]
Maybe those can go under an "Advanced" section. You or someone else would have to write that because I'm not familiar at all with those.

**Comment by dngray** [comment]
I'm thinking we should also incorporate https://github.com/privacyguides/privacyguides.org/pull/1979 into this, as a tip or something like that.

**Comment by dngray** [comment]
As a part of https://github.com/privacyguides/privacyguides.org/discussions/1281 we should mention how to update "macOS".

**Comment by dorkbuttt** [comment]
As MacOS Sonoma 14 is still in beta, I thought it would be prudent to mention it here instead of a separate issue. Apple is dropping support for its legacy plug-ins in Mail.app, disabling GPGTools from being enabled and thus able to decrypt messages. So the entry of it in Email Clients is on a course of being out of date. My first instinct is to retreat to Thunderbird for MacOS, unless word can be ascertained by the developers that they are going to be moving forward and adapting to this change somehow. 

https://www.privacyguides.org/en/email-clients/#apple-mail-macos

https://www.macrumors.com/2023/06/14/macos-sonoma-drops-legacy-mail-app-plug-ins/
