### ISSUE TITLE
Add Hardware Section

### ISSUE THREAD

**Issue by maltfield** [privacyguides/privacyguides.org#1899]
# Request: Add "Hardware" Section

Can you please add a "Hardware" section to the Privacy Guides website?

## Why?

Good operational security also includes careful selection of hardware, especially for hardware that's **used to generate/store private keys**.

Not all of this hardware is created equal. Some is more open. Some is more trustworthy. And some vendors, well, we have historic reasons to distrust them.

## Examples

Some examples of privacy/security-related hardware:

1. Laptop vendors like [Purism](https://puri.sm/) or [Qubes-certified](https://www.qubes-os.org/doc/certified-hardware/) laptops like the [PrivacyBeast](https://insurgo.ca/produit/qubesos-certified-privacybeast_x230-reasonably-secured-laptop/) and [NitroPad](https://shop.nitrokey.com/shop?&search=nitropad)
2. U2F/WebAuthn [hardware tokens](https://en.wikipedia.org/wiki/WebAuthn)
4. NitroKey or LibremKey or similar devices to [verify boot](https://github.com/osresearch/heads) authenticity (protection from Evil Maid attacks)
5. [BusKill](https://en.wikipedia.org/wiki/BusKill) laptop kill cords or other hardware [Dead Man Switches](https://en.wikipedia.org/wiki/Dead_man's_switch)
6. Cryptocurrency hardware wallets
7. [USB Condoms](https://en.wikipedia.org/wiki/Juice_jacking#Mitigation)
8. True random number generators
9. TPMs
10. Biometric input devices
11. Webcam covers
12. Microphone blockers
13. Privacy screens
14. etc

#### Meta

(meta: when creating an issue on GitHub, the `Suggest a New Provider or Software` option links to a page that says the page doesn't exist https://discuss.privacyguides.net/c/suggestions)

**Comment by mfwmyfacewhen** [comment]
I like the idea, a few notes:
1. I don't think it makes sense to recommend specific machines, it matters more what's running on them and that the hardware is still receiving firmware updates from the OEM more than anything I think
7. This one doesn't seem necessary as it's the job of the TPM, Secure Enclave on apple devices, etc to handle all encryption. They include a true random number generator
10. This is one that maybe we shouldn't recommend, it can cause damage to a laptop when you close it
11. Not sure how a microphone blocker would work, do you have any examples?

On top of your suggestions I think we'd want to include something on home networking equipment as well.

**Comment by maltfield** [comment]
> Microphone blockers: Not sure how a microphone blocker would work, do you have any examples?

These are basically just 3.5mm TRRS jacks with nothing connected to them. If you just take a pair of (preferably old & broken) pair of headphones w/ a microphone and cut off the jack, you have a microphone blocker. But they also sell them on privacy stores. Your laptop detects that a microphone is plugged-in, and it switches input from the built-in microphone to the plugged-in microphone, which doesn't exist. Simple.

They also sell USB ones. Same thing: it identifies itself to the computer as a microphone, but there actually isn't one. Example:

 * https://www.amazon.com/Privise-Original-Microphone-Protection-Smartphone/dp/B07L1QYVYF/

Example

**Comment by mfwmyfacewhen** [comment]
Interesting, thanks for the explanation on mic blockers, that seems like a good thing to make people aware of. The hardware vendor thing is concerning, maybe we'll recommend that people nuke the preinstalled OS and install a fresh version of windows/linux, since I think maintaining a comprehensive list of all the vendors caught doing that would give people a false sense of security if they're computer is from a vendor that hasn't done that before.

**Comment by mfwmyfacewhen** [comment]
Should probably combine #1864 with this.

**Comment by maltfield** [comment]
> The hardware vendor thing is concerning...I think maintaining a comprehensive list of all the vendors caught doing that would...

Well, the list of vendors doing bad things is exceedingly long. I don't think it's necessary to maintain that list, but I do think it's necessary to have a notebox that explains this risk and maybe a few citations for examples.

On the other hand, the list of vendors who are privacy-focused and trustworthy is very small. That *is* a list that I think should be explicitly enumerated on privacyguides.org

**Comment by maltfield** [comment]
>  doubt microphone blockers have any effect?

If your OS is not compromised, it does have an effect. I am not an Android developer, but I don't think apps can choose which microphone to listen-to.

> Better to use external mic and remove internal one, if this is part of your threat model.

Definitely that's better. But I do think the mic blockers are a valid solution for many people who just want to stop non-malicious alexa, cortana, ok google, or whatever apps that are always listening from being able to hear for a bit

**Comment by maltfield** [comment]
> i think encrypted drives are a good addition here.
> perhaps bugdetectors, hotel alarms for a travel section.

personally, I think history shows that FDE belongs in software, not hardware.

> bugdetectors, hotel alarms for a travel section.

I'm skeptical of the efficacy of such tools. Regarding travel, I do think [Haven](https://guardianproject.github.io/haven/) deserves a mention, but probably not in the hardware section.

**Comment by mfwmyfacewhen** [comment]
I definitely don't want to recommend anything unless it's absolutely proven effective, and I'm not sure that bug detectors fit that description. It seems like an [effective bug sweep](https://www.youtube.com/watch?v=6mojBV4aN58) isn't feasible for the average person who isn't willing to drop thousands of dollars on equipment and training. Don't want to give people a false sense of security. Hotels usually have locks that only lock from the inside as well as the regular lock, so I'm not sure how necessary hotel alarms are.

Haven looks interesting, although surveillance apps might be out-of-scope for PG.

I like the nail polish idea. The anti-interdiction is nice, I think google has a similar thing? I can't remember.

**Comment by mfwmyfacewhen** [comment]
> I have often been in hotels that do not have this door lock, it has proven to be effective in a personal case for me.

Might be good to mention it then, do you have any particular products in mind or are they all mostly the same?

> As for hardware usb drives I tooted today: https://mastodon.social/@ph00lt0/109664857214746240
> These are really good tools that software cannot compete with as this won't work f.x. with a mobile phone, but also generally these hard drives are more secure.

Might have you write that part as I'm not familiar.

**Comment by mfwmyfacewhen** [comment]
> > Haven looks interesting, although surveillance apps might be out-of-scope for PG.
> 
> @mfwmyfacewhen It is unmaintained and most of its functionality no longer works

Ah then I definitely won't mention it, thanks for the heads up.

**Comment by mfwmyfacewhen** [comment]
@maltfield I was looking on the GitHub for Buskill and I noticed the app seems to still be in beta, do you think it's fairly stable and usable? Generally we don't like to recommend beta software.

**Comment by maltfield** [comment]
@mfwmyfacewhen BusKill is in beta like Gmail was in beta (for 5 years, very stable, but with better features being added). It being "beta" is probably not what you think..

BusKill is fully functional on all three target platforms. Currently it's very simple, but it does what it says it does: it locks your screen when a USB drive is removed and it's armed.

Disclaimer: BusKill is my project.

**Comment by mfwmyfacewhen** [comment]
Thanks! Just wanted to make sure.

**Comment by mfwmyfacewhen** [comment]
@ph00lt0 Ready for you to write about encrypted drives if you have the time

**Comment by maltfield** [comment]
Re: https://discuss.privacyguides.net/t/please-add-hardware-recomendation-section-all-categories/11616

I've always wondered if there was actually a wireless microphone and/or wireless speaker on the market that was designed from the ground-up with security in mind

**Comment by maltfield** [comment]
In the link above, the user also mentioned Purism.

> laptos (right now , the best i could fiind is the librem 14 laptop with the boot usb)

Today I discovered a list of "competitors" to purism, which they openly linked-to from their blog because they considered them "friends & allys" over competition.

> Purism has a few indirect “competitors” in the GNU/Linux community, but we actually consider them as allies working toward the same goal, with a different approach. If you feel like Purism’s offering does not suit you, please consider these companies that also put an emphasis on Free Software:
>
>>    If you are interested in solid, well-made older laptops (from before Intel introduced the Management Engine in all of its chips in 2008) that currently have a 100% free BIOS and already have the FSF’s RYF certification, you should consider the various laptops from [Vikings](https://store.vikings.net/libre-friendly-hardware/x200-ryf-certfied), [Libiquity](https://shop.libiquity.com/product/taurinus-x200) or [Technoethical](https://tehnoetic.com/laptops).
>> 
>>    If you’re looking for workstations or servers with a freed BIOS, consider Vikings’ D16 workstation or D16 rackmount server.
>>
>>    If you are interested in an amazing open-hardware DIY computing platform, you should support [Novena](https://www.crowdsupply.com/sutajio-kosagi/novena).

[Again](https://github.com/privacyguides/privacyguides.org/issues/1899#issuecomment-1377408220), the list of privacy-friendly laptop manufacturers is so small, I think it's worthwhile that we actually enumerate them in this guide.

**Comment by dngray** [comment]
> Laptop vendors like [Purism](https://puri.sm/) or [Qubes-certified](https://www.qubes-os.org/doc/certified-hardware/) laptops like the [PrivacyBeast](https://insurgo.ca/produit/qubesos-certified-privacybeast_x230-reasonably-secured-laptop/) and [NitroPad](https://shop.nitrokey.com/shop?&search=nitropad)

Keep in mind we won't be recommending any "libre" laptops aka ancient Intel platforms (3rd gen) in the name of privacy. We do not want to give off the signal that you need these laptops for any kind of privacy.

**Comment by maltfield** [comment]
> There may be more room for vendors like Purism (which is at least 10th gen), System76, Starlabs

I would be very happy if we could just link to Purism, System76, and Starlabs.

Most people literally don't know there are options besides the major players like HP, Lenovo, Asus, Acer, Apple, etc. I do hope we can link to at least a few of those privacy-focused alternative vendors so that users are aware that better alternatives are out there..

**Comment by maltfield** [comment]
@mfwmyfacewhen I have some very strong differences of opinion of sbeve's comments on the forums, so please take anything they say with a grain of salt. They're giving very bad advice that's not appropriate for high-risk users (journalists, whistleblowers, activists, human rights defenders, crypto traders, etc)

**Comment by maltfield** [comment]
> How are those vendors better?

Transparency, free software, security features, and privacy. Purism is by far the most secure vendor out there. I don't know of any other vendor that's FSF certified and integrates Heads into their boot setup to cryptographically verify the authenticity and integrity of the firmware using keys that you contorl.

**Comment by tlaurion** [comment]
Hey all.
Jumped Herr from haven call for leadership ticket that was referred from here.

Heads maintainer here.

I would love to pinpoint everyone to this issue which explains differences of architectures and platforms supported by Heads project.

https://github.com/osresearch/heads/issues/692


The point here, with Purism/Insurgo/Nitrokey and other makers jumping into coreboot now, is that coreboot alone is not a guarantee of privacy.

Intel ME neutering is a thing, deactivating is another. And depending of ME features provided, it may or not break features to remove or deactivate it, depending of how it is done.

RYF certification from FSF won't happen for reasons I covered under Qubes forum numerous times. Unfortunately with current state of things, I would agree that RYF certification is not a guarantee for privacy, since privacy is bound to security until a certain point, where all laptops/servers outside of kgpe-d16 and Talos II are not providing microcode update because of FSF policies, and that is currently endangering privacy to some extent.

I would love to invite discussions into where those hardware recommendations/endorsement should happen, and that is upstream in projects that are integrating coreboot for security/privacy reasons.

Its hard to recommend a platform versus another in current days. Newer platforms require non neuterable ME on Intel, and FSF blobs inside of coreboot which is not initializing the hardware itself anymore, where AMD is rarer outside of Chromebooks which come with a different way of computing, considering everything is cloud based and not offering sufficient storage nor ram.

Its complicated but if the goal is to have a discussion on those topics, I would have a lot to say.

Threat modeling. Threat modeling. Threat modeling. 

Insurgo here, feel free to contact me from details on my webpage.

**Comment by maltfield** [comment]
Also, I'll add that since our discussion above, I did get a chance to play with Heads (via PureBoot) myself. I found PureBoot to do a lot of handwaving, so I published the following guide that outlines Coreboot, Heads, and the tech that went into it, which I think will be beneficial for anyone who needs a quick background of this tech

 * https://tech.michaelaltfield.net/2023/02/16/evil-maid-heads-pureboot/

**Comment by tlaurion** [comment]
@maltfield I reiterate that this write up is a must read.

**Comment by mfwmyfacewhen** [comment]
> Just wanted to chime in and ask if the tools listed here are considered.
> 
> [privacytools/privacytools.io#904 (comment)](https://github.com/privacytools/privacytools.io/issues/904#issuecomment-586592856)

Thanks for the suggestions! After looking over the list:

Lindy USB port locker: As a lock picking lawyer subscriber, the claim that this will somehow protect your USB ports from a government agency seems dubious. I don't want to recommend something that will give people a false sense of security.

Mic blocker: as covered earlier in this thread, the currently selected audio device isn't really a security feature and might get bypassed. The proper solution is sandboxing with a microphone permission enforced by the OS.

Anti-spy RF scanner: Discussed something like this in the [issue](https://github.com/privacyguides/privacyguides.org/issues/1899#issuecomment-1377783009). Being able to reliably detect devices based on RF signals takes proper training and experience. I don't want to give the impression that you can just buy one of these off the shelf and find any malicious devices near you.

USB data blocker: I'd rather just tell people to plug their phone into the wall using a wall adapter or a battery pack rather than recommend these products which or may not properly protect the device. Modern phones also require you to explicit grant permission before allowing data access.

Tableau forensic bridge kit: This just seems like a forensics tool, not sure what the privacy benefit of it would be.

StarTech 1:5 USB flash drive duplicator and eraser: This is just a USB duplicator. Again not sure the privacy benefits here. Any computer can erase a flash drive as well, it's not necessary to buy a dedicated device to do that.

StarTech 4-bay drive eraser: Same thing but for hard drives. I don't think there's any privacy benefit here.

Lowell Destruct hard drive eraser: If you want to erase a hard drive, then you can just do that in your OS, don't need a dedicated device. This thing reminds me of USBKill, which makes me very nervous. I *really* don't want to recommend something like this.

Apricorn Aegis Padlock Fortress FIPS USB 3.0 hard drive: Looks fine, I did write a bit on FIPS drives. I don't really want to recommend a specific one since it's a standard.

Brick House Security stuff: Looks like they sell GPS trackers and hidden cameras and whatnot? This is antithetical to privacy and won't be recommended.

BusKill: Already recommended, although I need to expand on it a bit.

White Noise Audio Jammer AJ-34: Not sure how effective this one is in practice. I imagine if it's loud enough to stop microphones from being able to hear you, then it would stop the person you're talking to from being able to hear you as well. Also it's just a speaker that makes noise. That could be achieved with any speaker that you already have laying around.

Let me know what yall think.
