### ISSUE TITLE
Emojis are not working w/ privacy plugin

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#2063]
Tracking two separate issues I'm having with the mkdocs-material privacy plugin:

1. Adding emojis to a page (like `:gear:` on tor.md) results in a broken image because the privacy plugin is not replacing the asset correctly:

   ![Screenshot 2023-03-01 at 13 59 09@2x](https://user-images.githubusercontent.com/3637842/222252465-fb22b7cd-95f0-497d-bf5d-56e4723547d1.png)

   The broken image is due to CSP not allowing external assets, not because the external asset doesn't exist and the plugin couldn't grab it.

2. ~~Adding a flag emoji to a page, for example `file-sharing.md` here, results in a build failure.~~ **Fixed** upstream.

**Comment by kamilkrzyskow** [comment]
The traceback shows that the issue is related to the `privacy` plugin. Maybe try to make an minimal example and check it's not a bigger issue with that plugin specifically.

**Comment by kamilkrzyskow** [comment]
In your most recent deployment preview https://app.netlify.com/sites/privacyguides/deploys/63ff870b6a65bc0008b0fe28
There is:
```
6:11:29 PM: INFO     -  Downloading external file: https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/2699.svg
6:11:30 PM: INFO     -  Downloading external file: https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/2764.svg
```
which indicates that it works. GitHub search didn't show any results but a local file search has lead me to multiple built files including:
https://github.com/privacyguides/privacyguides.org/blob/main/docs/tor.md?plain=1#L83
```
... :gear: ...
```
So it does partially work 🤔

**Comment by jonaharagon** [comment]
I can't reproduce my `:gear:` issue on a minimal install which means I'll have to keep poking at it even though it makes no sense. The flag issue is an actual upstream issue that I opened a bug report about now.

**Comment by squidfunk** [comment]
It seems to be related to how lxml handles Unicode. It's a mess.

**Comment by kamilkrzyskow** [comment]
> I can't reproduce my `:gear:` issue on a minimal install which means I'll have to keep poking at it even though it makes no sense. The flag issue is an actual upstream issue that I opened a bug report about now.

It works on my TempFork from yesterday, so it's likely another issue with the HTML.

**Comment by jonaharagon** [comment]
If I remove `pymdownx.details` from the markdown extensions in `mkdocs.common.yml` my `:gear:` emoji issue is fixed, but I can't reproduce this with a minimal install yet so I'm still not sure if it's ultimately an issue here or upstream 🤔

**Comment by jonaharagon** [comment]
> however I don't understand how exactly CSP influences this:

Our CSP blocks loading images from external sources. This is a privacy decision, obviously we could just fix it by adding cdnjs.cloudflare.com to the CSP, but the privacy plugin is _supposed to_ convert the image `src` from `https://cdnjs.cloudflare...` to `assets/external/cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/2699.svg` and serve it locally, but in this case that is not working for some reason.

**Comment by jonaharagon** [comment]
The plot thickens, removing [any of these three lines](https://github.com/privacyguides/privacyguides.org/blob/main/config/mkdocs.en.yml#L135-L137) from the mkdocs config *also* fixes the issue with the gear emoji on the tor page, which makes no sense 🤔

**Comment by kamilkrzyskow** [comment]
> The plot thickens, removing [any of these three lines](https://github.com/privacyguides/privacyguides.org/blob/main/config/mkdocs.en.yml#L135-L137) from the mkdocs config _also_ fixes the issue with the gear emoji on the tor page, which makes no sense 🤔

It feels almost random... squidfunk last time said that changing the order of the plugins in the mkdocs.yml file doesn't affect the order of execution, because the privacy plugin uses the MkDocs event priorities. However, he also said that it works concurrently, so maybe there is an edge-case where instead of the replaced private resource it gets the results from another Markdown parser without the replaced path 🤔. In the Netlifly log the resource was downloaded, but the path wasn't replaced. Those emojis are used on multiple pages, so maybe another page triggered the download and got a correctly swapped path, and the issue lies primarily in the tor.md file 🤷

**Comment by squidfunk** [comment]
> However, he also said that it works concurrently, so maybe there is an edge-case where instead of the replaced private resource it gets the results from another Markdown parser without the replaced path

That _could_ be a bug in the plugin, but it would be surprising, as we deliberately reconcile all downloads before applying replacements. Specifically:

1. [Find all images in `on_page_content`](https://github.com/squidfunk/mkdocs-material-insiders/blob/01bd4b8f6dde5874df4bdff818977be9934b7bcf/src/plugins/privacy/plugin.py#L132-L158) and enqueue them for downloading.
2. [Reconcile](https://github.com/squidfunk/mkdocs-material-insiders/blob/01bd4b8f6dde5874df4bdff818977be9934b7bcf/src/plugins/privacy/plugin.py#L160-L170) after parsing all _rendered_ Markdown files (= HTML) for external images and downloading them.
3. [Replace external assets](https://github.com/squidfunk/mkdocs-material-insiders/blob/01bd4b8f6dde5874df4bdff818977be9934b7bcf/src/plugins/privacy/plugin.py#L192-L199). There _might_ be other assets in the final HTML (plugins may add images to templates like the `git-authors-plugin`), which is why they [need to be downloaded synchronously](https://github.com/squidfunk/mkdocs-material-insiders/blob/01bd4b8f6dde5874df4bdff818977be9934b7bcf/src/plugins/privacy/plugin.py#L343) ([no `concurrent` flag](https://github.com/squidfunk/mkdocs-material-insiders/blob/01bd4b8f6dde5874df4bdff818977be9934b7bcf/src/plugins/privacy/plugin.py#L363)).

There could still be race conditions. I tried to think of all cases – I recommend to read the comments in the plugin. If a reproduction could be provided, that would be amazing. Happy to fix it and improve the plugin.

**Comment by jonaharagon** [comment]
I was making this way too complicated in my head. I think this is just a matter of it not handling **a lot** of external resources on a page correctly. Add enough gears and eventually it breaks:

<img width="1562" alt="Screenshot 2023-03-01 at 17 05 26@2x" src="https://user-images.githubusercontent.com/3637842/222286961-83c4fde3-d804-4d11-9c97-ff2efed578c8.png">

@squidfunk I can easily reproduce this on a two-file install: [Archive.zip](https://github.com/privacyguides/privacyguides.org/files/10866029/Archive.zip)

**Comment by kamilkrzyskow** [comment]
The plugin wasn't always concurrent, right? Then maybe an older version of the plugin without concurrency might show different results and therefore reassure the idea of it being an issue with the concurrent design itself 🤔However, I don't know if the fix today was related to concurrency or if it fixed something else entirely.

**Comment by jonaharagon** [comment]
Since this does seem to be an upstream plugin issue I'll close this and track https://github.com/squidfunk/mkdocs-material/issues/5127 instead :)
