### ISSUE TITLE
404 page not displayed correctly

### ISSUE THREAD

**Issue by razac-elda** [privacyguides/privacyguides.org#2084]
I tested this behavior on Firefox and Brave.

Example page: https://www.privacyguides.org/en/advanced/test/

![Screenshot](https://user-images.githubusercontent.com/30749146/224328805-7bd799bb-ebfc-4b52-9300-73a46a6976a3.png)

**Comment by noClaps** [comment]
This happens because the assets use relative links in their sources. For example:
```html
<link rel="stylesheet" href="../assets/stylesheets/main.dc5b59cc.min.css">
```
At a link like https://www.privacyguides.org/en/advanced/test/, it searches for the assets in the `/en/advanced/assets/...` folder, which doesn't exist. If you go to https://www.privacyguides.org/en/test/, the normal 404 page loads since the assets are now loading from the correct location.

All you need to fix this is to change the CSS and JS sources to make them absolute links.
