### ISSUE TITLE
Clarify data breach risk with OAuth

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#2207]
### Affected page

https://www.privacyguides.org/en/basics/account-creation/#sign-in-with-oauth

### Description

An advantage of OAuth that we list is:

> Security: no risk of being involved in a [data breach](https://en.wikipedia.org/wiki/Data_breach) because the website does not store your credentials.

It should be clarified that there's no risk in your authentication data being leaked if *the external website you're registering on* suffers a data breach. Obviously if the OAuth provider themselves experiences a data breach, your data would be vulnerable in that case.

### Sources

n/a

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by nopeitsnothing** [comment]
You should also mention things like Facebook OAuth and login security. This process grants 3rd party apps the ability to use your session tokens to takeover your account. This is common and many people assume "I've been hacked!!!1!". In reality, the app has stolen your session, and can use this to do any number of things. It can masquerade as you. It can gather details that can help pivot to fraud, in some cases.

[Facebook login](https://developers.facebook.com/docs/facebook-login/) is a huge danger because it offers convenience over privacy and security.

For example, see[ their own documentation](https://developers.facebook.com/docs/facebook-login/security) of the process:

- exposure to malware and spammers
- leaking tokens in your dev environment, if you use it for your own app
- token hijacking
- stale tokens tend to be vulnerable
- cross-site request forgery (CSRF)
- malicious redirects (malware delivery)

![](https://i.ibb.co/YWdyH0m/oauth-mitm.png)

The list goes on. This is just for Facebook OAuth, but it applies to any OAuth entity.

When a malicious app (or "PUP", potentially unwanted program) gains a foothold, it can use that access to not only escalate its own permissions but exfiltrate data from your app or your account on the intended destination. It can then gather phone numbers, addresses, etc. in an attempt to get control of your email and phone (SIM swap) to prevent fraud alerts from reaching you.

Be careful with OAuth.
