### ISSUE TITLE
Remove LibreOffice for Android and iOS/iPadOS links

### ISSUE THREAD

**Issue by quackerex** [privacyguides/privacyguides.org#2213]
### Affected page

https://www.privacyguides.org/en/productivity/#office-suites

### Description

There are no android Android or iOS/iPadOS version of LibreOffice.
Instead iWork suite can be recommended for iOS/iPadOS.
Related: https://github.com/privacyguides/privacyguides.org/pull/2150#issuecomment-1612387148

### Sources

https://www.libreoffice.org/download/android-and-ios/

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by jonaharagon** [comment]
These are the official LibreOffice mobile apps, and we link to LibreOffice’s site directly with these links to clear up this confusion. 

We wouldn’t want to add Collabora as a separate recommendation, because it doesn’t make sense to use it over LibreOffice’s direct releases for non-enterprise users.
