### ISSUE TITLE
'Irrevocable' privileges of Google Play services misrepresented

### ISSUE THREAD

**Issue by notahomosapien** [privacyguides/privacyguides.org#2233]
### Affected page

https://www.privacyguides.org/en/os/android-overview/#choosing-an-android-distribution

### Description

> Google Play Services, which has irrevocable privileges to access your files, contacts storage, call logs, SMS messages, location, camera, microphone, hardware identifiers, and so on.

All the privileges stated here can be revoked except access to hardware identifiers in Settings, even on the most bloated devices which don't allow the user to disable even the Google app for some reason.

### Sources

Permissions Page of Google Play services in app settings

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

**Comment by nopeitsnothing** [comment]
> Google Play Services has irrevocable privileges

This is a factual statement. It requires Phone, SMS, and Storage, [each with sub-permissions](https://play.google.com/store/apps/details?id=com.google.android.gms) for you to be able use your phone like normal. Otherwise, you break the system functionality and it cannot work as intended, and will annoy you to reapply the settings.

The Phone is required to:
- modify phone state
- read call log
- directly call phone numbers
- reroute outgoing calls
- read phone status and identity
- write call log
- directly call any phone numbers
- add voicemail

The SMS is required to:
- send SMS messages
- read your text messages (SMS or MMS)
- receive text messages (MMS)
- receive text messages (SMS)

The Storage is required to:
- read the contents of your USB storage
- modify or delete the contents of your USB storage

**Comment by notahomosapien** [comment]
> Otherwise, you break the system functionality and it cannot work as intended, and will annoy you to reapply the settings.

That does not matter. There is a difference between 'can break functionality' and 'irrevocable'.

**Comment by notahomosapien** [comment]
> To revoke a permission e.g. Phone you would need to reapply it anyway to use some features.

But this does not mean that the atricle has to falsely say that those permissions (SMS, Storage, Phone) are "*irrevocable*".

**Comment by nopeitsnothing** [comment]
It's a technical statement: you can remove them but you will be forced to reapply them later, so it's moot.

**Comment by notahomosapien** [comment]
> It's a technical statement: you can remove them but you will be forced to reapply them later, so it's moot.

That has nothing to do with this article/blog falsely claiming that '*Google Play Services, which has irrevocable privileges to access your files, contacts storage, call logs, SMS messages, location, camera, microphone, hardware identifiers, and so on.*' (Note that everything stated is revocable except access to hardware identifiers and Location)
