### ISSUE TITLE
Windscribe server seizure self disclosure

### ISSUE THREAD

**Issue by yegors** [privacyguides/privacyguides.org#224]
Hi folks,

This is in regards to the addition made here: https://github.com/privacytools/privacytools.io/pull/2395 ("Known Privacy Related Incidents & Gag Orders to Date" list)

This is an unfair inclusion in this list, as it's unlike all the others. You've highlighted our entirely voluntary self disclosure of the Ukrainian server seizure incident, where we have no good reason to believe that this was exploited in the short period that it took to rotate keys, as the vector for the attack is highly challenging (explained in our blog further below). 

We could have said nothing at all, like most other providers who had identical incidents (Express, PIA, TorGuard and Nord, latter 2 of were actually compromised and hid this fact until it leaked online). You would never know about the Windscribe incident if we were not honest with our users. Every single other occurrence confirms cooperation with law enforcement, or an arrest of some kind. This was a precautionary and voluntary disclosure on our part, and it's rather unfair to be included. People make mistakes, we took full responsibility, self disclosed the issue (to our determent), and fixed it.  

Additionally, almost every VPN out there is vulnerable to the exact same thing, right now. Including those who already had an incident before. This is empirically testable by anyone. 
https://blog.windscribe.com/ukrainian-server-seizure-a-commentary-and-state-of-the-industry-e71e8d205b26/

If Windscribe is included, everything else should be included too. Although I'd argue, those who brushed this under a rug with their legions or PR people are far worse, but dishonesty clearly works, since they're not included in this list of "Known Privacy Related Incidents & Gag Orders to Date". 

Look forward to your thoughts on the matter.

**Comment by Loki-L1130** [comment]
@yegors Do you plan to make a No-Logs Audit ?

Though, You are a very Trusted and Transparent company in my Opinion. Though Still some folks consider the Fives Eyes Country as a criteria for Qualification. Despite, the fact that it is unnecessary to consider and being used to determine a Service rather than Deep Investigation of service.

Still this makes a major leap along with other Audits including Apps (This is crucial as Companies like Zerodium is looking into exploit many other Big Players, making an audit for Apps will be good a lot and makes Windscribe safer from those companies. I saw your Quote Tweet. Great work on intimating this to other People) and Server Infrastructure.

**Comment by dngray** [comment]
> @dngray, They seemed to be looking Forward to Open Source the Apps too. Which is actually great including the Provisiong System is also to be Open-Source. So, It is great

I think at this point we'd actually add the to our VPN page, as a recommended provider.

**Comment by yegors** [comment]
@Loki-L1130 
Yes, this is on our roadmap after the new infra is live. 

My issue with the whole "5 eyes" thing and some people considering this part of the criteria is simply the fact that the inception has already been performed, by VPN marketing ("review) sites.  People think this is a requirement simply because every blogger who wants to make a quick buck promoting VPNs will say this, to promote offshore based VPNs of the well known snakeoil salesmen you see sponsoring your favorite Youtube channels. 

Every reviewer that I spoke to that was somewhat reasonable always said something like: "Yeah, it probably doesn't matter, but everyone says this, so we will too". 

I personally think this is no different than doctors recommending smoking as a good thing, as they did in 1950s.

**Comment by dngray** [comment]
> My issue with the whole "5 eyes" thing and some people considering this part of the criteria is simply the fact that the inception has already been performed, by VPN marketing ("review) sites. People think this is a requirement simply because every blogger who wants to make a quick buck promoting VPNs will say this, to promote offshore based VPNs of the well known snakeoil salesmen you see sponsoring your favorite Youtube channels.

We're looking at removing that from the criteria as a part of the PR addressing https://github.com/privacytools/privacytools.io/issues/1437

The reason is I'm certain there dozens of other intelligence gathering agreements that probably have no name, but are just as dangerous if you run a server in the countries that they exist.

> Every reviewer that I spoke to that was somewhat reasonable always said something like: "Yeah, it probably doesn't matter, but everyone says this, so we will too".

It's something very from 2010-ish era when  Snowden's made his releases. Prior to Snowen a lot of what he said was suspected especially with regard to [Room 641A](https://en.wikipedia.org/wiki/Room_641A) and the whistleblower from [Mark Klein](https://en.wikipedia.org/wiki/Mark_Klein), however as there weren't documents marked as "secret" it never really got traction with the media.

I think in a way it was because people were concerned about current events at the time and that marketing companies wanted to capitalize off those events.
