### ISSUE TITLE
Add RSS Feed to Blog

### ISSUE THREAD

**Issue by jonaharagon** [privacyguides/privacyguides.org#25]

**Comment by rottenstonks** [comment]
@jonaharagon Any news on this? Resources, comments...

**Comment by p2635** [comment]
I'd also love to follow the blog, subscribing to this issue

**Comment by arcticlex** [comment]
> I'd also love to follow the blog, subscribing to this issue

I was looking through the issues, saw this one, and was quite confused since I've been following the RSS feed already. 

https://privacyguides.org/feed.xml already exists and features the full blog contents.

**Comment by Loki-L1130** [comment]
May be they had it set up but forget to close the issue. @dngray Can you close this ?

**Comment by p2635** [comment]
Works for me, thanks

**Comment by dngray** [comment]
> May be they had it set up but forget to close the issue. @dngray Can you close this ?

While the RSS feed does exist we should advertise it more publicly, I suggest we add to the top of the page so that it can be detected ie [RSS Autodiscovery](https://www.rssboard.org/rss-autodiscovery):

```html
<link rel="alternate" type="application/rss+xml" 
  title="Blog | Privacy Guides" 
  href="https://privacyguides.org/feed.xml" />
```

We should also make some sort of note on https://privacyguides.org/blog/ that RSS is available, even if it's the RSS logo etc.

@lx-is It would also be nice if you could look into a JSON feed as you mentioned in https://github.com/privacyguides/privacyguides.org/pull/671#issuecomment-1056110270

**Comment by lx-is** [comment]
> @lx-is It would also be nice if you could look into a JSON feed as you mentioned in [#671 (comment)](https://github.com/privacyguides/privacyguides.org/pull/671#issuecomment-1056110270)

Oh yeah, forgot about that. I'll look into it.

**Comment by dngray** [comment]
This one is now fixed.
