### ISSUE TITLE
Strongbox Password Manager is not Open Source - needs to be corrected

### ISSUE THREAD

**Issue by pictosun** [privacyguides/privacyguides.org#2649]
### Affected page

https://www.privacyguides.org/en/passwords/

### Description

You're writing, that Strongboxsafe is an Open Source Password-Manager. But that's not true, as it is not Open Source.

Don't know if they changed it or never wrote about on their website:
But also see here: https://strongboxsafe.com/de/

### Sources

See here (the links within the posts):
https://github.com/strongbox-password-safe/Strongbox/issues/784

### Before submitting

- [X] I am reporting something that is verifiably incorrect, not a suggestion or opinion.
- [X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

**Comment by kimg45** [comment]
Looks like it [is](https://github.com/strongbox-password-safe/Strongbox) they just link to their GitHub on their site for some reason.

**Comment by jonaharagon** [comment]
Thanks for letting us know. I am fairly certain that was not the case when it was added.

**Comment by keepassium** [comment]
@jonaharagon, is this significant enough for your [earlier response](https://discuss.privacyguides.net/t/keepassium-used-to-be-listed-i-think-should-i-now-prefer-alternatives/12295/3)?

> We could look into Keepassium further if you could share specifically what you don’t like about Strongbox.

**Comment by pictosun** [comment]
> @jonaharagon, is this significant enough for your [earlier response](https://discuss.privacyguides.net/t/keepassium-used-to-be-listed-i-think-should-i-now-prefer-alternatives/12295/3)?
> 
> > We could look into Keepassium further if you could share specifically what you don’t like about Strongbox.

Good point. Will there be a native macOS version coming for Keepassium?

**Comment by keepassium** [comment]
> Will there be a native macOS version coming for Keepassium?

[There is one](https://github.com/keepassium/KeePassium/releases), both for Intel and Apple Silicon, based on Mac Catalyst.  (A framework for porting iOS apps to macOS.)

It has been stuck in beta for three years, though, because we cannot push it any higher than "good _enough_". Mac Catalyst does 80% of the job and we managed to fix another 10% with platform-specific code. But the remaining 10% are virtually impossible because of Apple's conversion layer. 

At this stage, I am considering to embrace "good enough" and just release it :)
