### ISSUE TITLE
Provide guidance on enabling HTTPS-Only mode

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#273]
## Description

Removal of https://github.com/privacyguides/privacyguides.org/pull/262 I decided we should provide instruction on how to enable HTTPS-Only mode in both Chromium/Firefox.

**Comment by BraINstinct0** [comment]
Leaving quick note on Chrome.
- Chrome
- * Starting from at Chrome 94, `chrome://settings/security` ->`Advanced` section->toggle `Always use secure connections` on. Unsure if it is on by default, or if it is since which version.
- * If not shown(i.e. on older versions), worth checking if `chrome://flags/#https-only-mode-setting` is set to `Disabled`. If so, switch it to `Enabled` or `Default` (which is equivalent). Not sure which version this flag was added.
- * Works on Windows, Linux, Chrome OS and Android.

(due to lack of patience) didn't write further; a quick search brought up a Link: **h**ttps://beebom.com/how-enable-https-only-mode-chrome-firefox-edge-safari/ .
