### ISSUE TITLE
Netguard may not be so helpful with Android 10 due to per app internet permission toggles

### ISSUE THREAD

**Issue by Mikaela** [privacyguides/privacyguides.org#279]
## Description

I was given this report in private.

**URL of affected page:** https://privacyguides.org/operating-systems/#aaddons

> fwiw, NetGuard is probably useless on android 10/11 (and possibly dangerous as it may be less effective) as android 10 introduces per app internet permission toggles
> (was looking at privacyguides)

I requested the reporter to open an issue at GitHub, but

> can't because they made the atrocious decision to use github
> which kinda destroys any credibility they might've had otherwise 🤷‍♀️

which is a subject for another discussion, that I am pretty sure has the label `contributing` , but somehow I am unable to find it even with direct label seasrch.

**Comment by dngray** [comment]
We might remove that entire section as Orbot hasn't been updated since April and was removed from F-Droid.

As for the reason for using github, that comes down to discoverability. Self hosting something like codeberg comes at the cost of certain features (such as github actions). Also discoverability.

**Comment by tommytran732** [comment]
> We might remove that entire section as Orbot hasn't been updated since April and was removed from F-Droid.
> 
> As for the reason for using github, that comes down to discoverability. Self hosting something like codeberg comes at the cost of certain features (such as github actions). Also discoverability.

Orbot is updated on Their own Fdroid repo (Guardian Project). In fact, this repo is included in the Fdroid client by default, you just gotta enable it.

**Comment by zecamigo** [comment]
I can confirm NetGuard is pretty useless in Android 10.
I use personalDNSfilter, although it doesn't allow to block network access on an App level basis.

**Comment by tommytran732** [comment]
There is no app internet permission toggle outside of Graphene afaik. There certainly wasn't one on my Android 10 phone.

That said, I think the main argument against NetGuard is that its leaky and an app can bypass it if it wanted to.

**Comment by ignoramous** [comment]
NetGuard's filtering features (where one can monitor *and* block individual IPs per-app) aren't replicated in AOSP 10+. Per-app toggles are removing capability to access the network for those apps, and that's about it.

>  which kinda destroys any credibility they might've had otherwise

This is just a cheap shot. GitHub is where most FOSS developers collaborate (like it or not) because GitHub is not only free (for FOSS repositories), but also actively helps developers manage a community, support a project, and help with seamless cross-border sponsorships. And, ironically enough, that same 'private report' isn't complaining about PrivacyGuides being on GitHub or hosted on Vultr, smh.
