### ISSUE TITLE
NextDNS isn't self-hosted

### ISSUE THREAD

**Issue by ignoramous** [privacyguides/privacyguides.org#321]
## Description

NextDNS doesn't run in its own data-centers (and, we _could_ confirm this with Olivier and Roman if that is still the case). They're mostly hosted in various co-locations and with BigCloud alternatives like Vultr.

Their ASN's BGP peering information gives a bit of insight in to who their infrastructure partners are: https://bgp.he.net/AS34939#_peers

**URL of affected page:** https://privacyguides.org/providers/dns/

Disclosure: I run both an open source [public DoH resolver](https://github.com/serverless-dns/serverless-dns) and build an open source DoH Android app: https://github.com/privacyguides/privacyguides.org/discussions/241

**Comment by jonaharagon** [comment]
Interesting. This makes me wonder what the importance and meaning of the "Hosting Provider" section actually is here. I would imagine the number of providers that are _actually_ entirely self-hosting on their own hardware in their own datacenters on their own IP space is probably exceedingly rare even among large providers.

It makes more sense to me to either replace this list (for all providers) with links to pages like https://bgp.he.net/AS34939#_peers that list all providers peered with them so that it is always accurate, or to remove the list of hosting providers entirely. I'm not sure the list really adds any value since generally the hosting providers in question don't have access or involvement with the actual operation of the providers. Thoughts @privacyguides/team?

**Comment by dngray** [comment]
This has been fixed in https://github.com/privacyguides/privacyguides.org/pull/767
