### ISSUE TITLE
Add Warning Labels to Matrix/Synapse

### ISSUE THREAD

**Issue by Mikaela** [privacyguides/privacyguides.org#50]
## Description

**URL of affected page:** https://privacyguides.org/software/real-time-communication/#federated

This is practically https://github.com/privacytools/privacytools.io/issues/2424 from where I am hoping for a warning label to be applied onto Element/Matrix.

* Per-room profiles leak in user-directory (problem for people coming from Discord and examples listed in issue comments): https://github.com/matrix-org/synapse/issues/5677
* Media redactions are never actually removed (direct links keep working): https://github.com/matrix-org/synapse/issues/1263
* Reactions in private rooms aren't encrypted: https://github.com/matrix-org/matrix-doc/issues/2678

**Comment by Flam3z** [comment]
I think an update from the developers should be needed as they have not responded to their issues in a while just so we can see what their current stance/progress on the said issues are.

**Comment by xanoni** [comment]
@Mikaela Thank you for reopening. Let's make sure we get to an answer this time. [Kind of strange that the previous issue was closed and archived](https://github.com/privacytools/privacytools.io/issues/2424), so I couldn't even add comments to it. But let's assume for now that there is no bad intent.

**On topic:**
I agree that Matrix indeed needs several warning labels related to Ephemeral / disappearing messages. My understanding is that in most common server/room setups, this feature simply can't be assumed to be existent. However, the most dangerous part is that the user could think that messages are actually being deleted when they are not.

**Non-exhaustive list of learnings that were non-obvious to me when I first started using Matrix:**
1) By default Synapse just sets something like a "hidden=true" flag when the user deletes messages, the messages are not actually removed from the database, but stored together with the "reason"
2) Even if you run your own home server, you don't know if other admins in the federation are also deleting messages from their drives
3) Due to the prevalence of bridges (and the fact that they are not always obvious/visible to the user), messages are forwarded to other networks where they are definitely NOT deleted

(I understand that ephemeral messages are never 100% secure, but at least an attempt should be made ...... or if not possible, the user should be warned.)

**Comment by jonaharagon** [comment]
> Kind of strange that the previous issue was closed and archived

I can't speak to why it was closed initially having not been resolved as I haven't been involved with the PrivacyTools side of things in quite a while, but that repo was archived because there are currently no active maintainers, the entire PrivacyTools team has moved to this project. Just an FYI.

**Comment by Flam3z** [comment]
Has matrix given a reason as to why those messages are still stored onto the server?

**Comment by Mikaela** [comment]
> Has matrix given a reason as to why those messages are still stored onto the server?

Assuming you mean media files, they say that multiple messages may point to the same media repo address and thus it's difficult to know when all messages pointing to the file are removed. That especially affects encrypted messages. This can be found from comemnts of https://github.com/matrix-org/synapse/issues/1263.

If you mean the servers storing removed messages for 7 days in general, that is for server administrators in case someone was abusive and redacting messages to remove proof of it. They are also planning to make those visible to room moderators. https://github.com/matrix-org/matrix-doc/pull/2815

**Comment by dngray** [comment]
Done in https://github.com/privacyguides/privacyguides.org/pull/192
