### ISSUE TITLE
Update private email provider Tutanota

### ISSUE THREAD

**Issue by zira** [privacyguides/privacyguides.org#507]
https://privacyguides.org/providers/email/

Tutanota now accepts bitcoin if you buy a tutanota gift card here who are official resellers as tutanota said https://digitalgoods.proxysto.re/

We are happy to let you know that you can now upgrade your secure Tutanota mailbox privately and anonymously by paying with Bitcoin or Monero! Just visit the Proxystore shop (official reseller of Tutanota) to order Tutanota gift cards and use these to upgrade your account. Your added gift card credit may be kept within your account for an unlimited time so that you can top up your account for multiple years. Please visit our pricing page to decide what gift card value best fits your needs.

**Comment by NSABackdoors** [comment]
Source for these claims? Tried finding it in their blog but to no avail.

**Comment by xibeifenghenhaohe** [comment]
> Source for these claims? Tried finding it in their blog but to no avail.

https://tutanota.com/faq/#cryptocurrency

**Comment by Dyrimon** [comment]
**Important note:** The voucher will only work on germany account, so you need to open the account in Germany (or connect to a Germany server from VPN or Tor I guess).

**Comment by jonaharagon** [comment]
This is a really strange restriction, because it not only requires going through a third-party which is offering these vouchers at an increased price, but also requires you to provide a German address when registering the account from the sounds of it (i.e. a German VPN would not suffice).

We could mention it, but while it may be "official" it is not a first-party payment method, so I'm equally inclined to not make any changes here. Thoughts @privacyguides/team?

**Comment by blacklight447** [comment]
Yeah, this isnt really what i would call supporting payment via crypto. Its just payment via thirdparty vouchers, which happen to support cryptoncurrencies.

Since their faq even states "we plan to add bitcoin as a payment method", it seems like they themselves admit that they don't really support it as of yet.

My vote goes to closing the issue, and then monitor for changes in their policy later on.
