### ISSUE TITLE
Software Suggestion | Session (ex-Loki) Messenger |  Decentralized

### ISSUE THREAD

**Issue by samcross021** [privacyguides/privacyguides.org#51]
Session Messenger is missing under Real-Time Communication - Decentralized.
The section Decentralized is removed. Please Re-evaluate the Section and Messenger.

https://github.com/privacytools/privacytools.io/issues/1678

**Comment by NSABackdoors** [comment]
I disagree that Session should be included as I don't think it's been battle-tested enough.

I also have concerns with both the Jurisdiction that Session is under (Australia) and the fact that the organization that Session is under (Oxen?) develops Session (Messenger), Oxen (Cryptocurrency), and Lokinet (Self-contained Network), which is an insane undertaking for any organization.

The fact that Signal got a lot of backlash was also because they planned on implementing Cryptocurrency into Signal which would fall under the IRS' jurisdiction. Although I am not fully familiar with Australian law so please inform me on whether this actually matters.
