### ISSUE TITLE
Encrypted DNS Resolvers: Add note to not to use with VPN

### ISSUE THREAD

**Issue by Asheq** [privacyguides/privacyguides.org#543]
I was reading through this page https://privacyguides.org/providers/vpn/#info, specifically the section titled `Should I use encrypted DNS with a VPN?`.
 
Based on that information, I think we should mention not to use encrypted DNS resolvers when using a VPN here: https://privacyguides.org/providers/dns/

**Comment by yegors** [comment]
It's not that simple, it depends on your use case. 

Positive:
- Your VPN provider won't see your DNS queries. IP based matching of destinations is more or less meaningless, since most things use CDNs, and the IP is shared by thousands of websites. If a VPN provider deploys deep packet inspection (captures all SNI) then they could log your browsing history. But why are you using a VPN provider that does this? 
- ECH will fix the above issue, but that's not gonna be supported for a while by most websites 

Negative:
- This is inherently a "DNS leak", albeit a self imposed one.
- It will add latency and slow things down since your DNS requests will go over the tunnel to the VPN server, which traditionally IS the DNS server, but in this case they will need to go further to your DNS provider which will always be slower. This is on top of TLS overhead that requires multiple round trips. 

Here is an example with made up latencies 

You ---> 10ms ---> VPN Server ---> 20ms ---> DNS server 

If you use your VPN server for DNS, latency is 10ms. If you use DOH/DOT on top of that, best case scenario is 30ms (TLS 1.3 0-RTT), worst case scenario is 90ms (3 roundtrips to establish a TLS session). This is assuming the DNS records are served from a cache, and don't require recursive resolution.

**Comment by dngray** [comment]
The intention is to include something like https://github.com/dngray/encrypted-dns#when-to-use-encrypted-dns

**Comment by DeiAsPie** [comment]
I don't think this understanding via a flowchart would make sense. We don't care whether someone want to encrypt something which is anyway gonna be in public domain yet it is always a recommendation to use https over http for a simple reason to elevate the entire playing field for privacy. There is no excuse to not encrypt your DNS whether or not using VPN/Tor for the same reason we all choose https over http. I know that doesn't technically hold but it would be still beneficial for all of us to use encryption on the DNS level with a trusted provider other than our ISP

**Comment by DeiAsPie** [comment]
Of course when using using TOR you don't use a DNS provider other than the one provided by the network itself.

**Comment by Asheq** [comment]
> Your VPN provider won't see your DNS queries. IP based matching of destinations is more or less meaningless, since most things use CDNs, and the IP is shared by thousands of websites. If a VPN provider deploys deep packet inspection (captures all SNI) then they could log your browsing history. But why are you using a VPN provider that does this?

Thanks for the detailed response @yegors. If I may summarize, the only reason to use an encrypted DNS resolver with a VPN is if you don't fully trust the VPN to not log your browsing history. If you use encrypted DNS, a malicious VPN could still *try* to log your browsing history but they would have to rely on the (far?) less accurate method of IP matching. The only downside is additional latency. Having to "trust" the encrypted DNS resolver is not an actual problem because the VPN masks your IP/identity from the resolver; you're not actually giving any additional trust (is this correct to say?).

**Comment by DeiAsPie** [comment]
One more possibly useful reason of using an encrypted DNS service would be to block connections to mischievous domains. Say you use a VPN and they do host their own recursive DNS resolver. But their DNS still uses a service like cloudflare on the back end and cloudflare is terrible at blocking malicious domains. Which means that you will have a secure connection indeed but to a domain that inherently is malicious. This can easily be fixed by setting up encrypted DNS like Quad9 which has a great record of blocking malicious domains.

Or you could use something like ahadns, blahdns, adguard, etc to get the best of both worlds, blocked ads trackers along with the privacy of your VPN. This is the my favorite setup.

**Comment by Asheq** [comment]
@DeiAsPie That's a good point. Essentially it grants you the freedom of choice: you get to use a DNS resolver of your own choice rather than be forced to your VPN's resolver.

**Comment by DeiAsPie** [comment]
And if you are worried that the system may ignore your intended DNS resolver completely in favor of the one provided by the VPN. Then that is not the case, the DoT server you set in Private DNS always dominates #561

**Comment by dngray** [comment]
Resolved in https://github.com/privacyguides/privacyguides.org/pull/767
