### ISSUE TITLE
Updating/correcting Wiki

### ISSUE THREAD

**Issue by DeiAsPie** [privacyguides/privacyguides.org#660]
# Few little things on the 'Page Criteria' of wiki can be improved for better

##  Here are a few of them:

Under Search Engines:
> - **Must not IP address log** should be changed to **Must not log IP Address**
> - **Must not do targeted advertising** should be changed to **Must not do targeted(behavioral) advertising**

***

## VPN criteria could also be extended to include
- Must have a No Logs policy
- Must have DNS leak protection
- Must be Independently Audited
- Must have Open Source Clients
- Must have Mobile Clients
- Must support IPv6 and WireGuard

***

## Search Engines could also be extended to include
- Should work flawlessly over a VPN/Tor

### Messengers could have
- Support strong end-to-end encryption (E2EE)
- Have been been independently audited

***

### Digital Notebook could have 
- Should support end-to-end encryption (E2EE) for notes

***

### Cloud Storage could include 
- Should support end-to-end encryption (E2EE)

***

### Calendar and Contact Sync Tools could include
- Should support end-to-end encryption (E2EE)

***

### In gerneral could include
- Unless truly advantageous things should be kept simple and minimalistic to reduce attack surface
- Software recommended should be Open-Source and if not it must go via rigorous discussion before being recommended
- Services recommended must have good privacy policy and should work over VPN and if possible over Tor too
- In case of two competing alternatives if nothing differentiates them technically then the service with a better reputation and willingness to stand for its users would be given an upper hand

**URL of affected page:**
https://github.com/privacyguides/privacyguides.org/wiki/Page-Criteria

**Comment by mfwmyfacewhen** [comment]
Nice, a few clarifications:
What do you mean by "strong e2ee"? Doesn't seem like that can be measured. Do you mean e2ee with perfect forward secrecy?
I don't agree with the open source thing, it really has nothing to do with how trustworthy a piece of software is imo, and really any recommendations should be hashed out in discussions regardless.
Clarification on what a "good privacy policy" is would be nice, like what specifically should be included?
Not sure how reputation and willingness to stand for its users are determined. Maybe replace this with something measurable like number of users.
Otherwise I like it!

**Comment by NSABackdoors** [comment]
> What do you mean by "strong e2ee"? Doesn't seem like that can be measured. Do you mean e2ee with perfect forward secrecy?

If strong E2EE meant PFS then wouldn't that make Session invalid?

> Unless truly advantageous things should be kept simple and minimalistic to reduce attack surface

I don't really see the use of adding this as it's too vague in my opinion. What makes a software simple and minimalist? Until we can answer that I don't think it should be added.

**Comment by realguyman** [comment]
> Must not do targeted/behavioral advertising

I disagree. "targeted advertising" already includes all methods used to target advertisements towards users, which requires collecting data on said users.

**Comment by realguyman** [comment]
@DeiAsPie I am closing this issue. Please keep _corrections_ and _additions_ separate. It's fine to “spam” us with a bunch of issues with small (or singular) issues, changes, additions, removals, etc. It makes it easier for everyone to tackle each individual issue rather than trying to evaluate all issues at once.

In addition to that, consider providing sources and research as to why we should make such a change.
