### ISSUE TITLE
Safari Sync Correction

### ISSUE THREAD

**Issue by mfwmyfacewhen** [privacyguides/privacyguides.org#737]
The Sync part of the Safari card is bit confusing and incorrect.

The synchronization of data is [not](https://support.apple.com/en-us/HT202303) end-to-end encrypted. Safari only encrypts Safari Bookmarks in transit and stores in an encrypted format.

Should change to

History, tabs, and iCloud tabs are end-to-end encrypted. However, bookmarks are [not](https://support.apple.com/en-us/HT202303). Although they are stored in an encrypted form, it is possible for Apple to decrypt them.

I think this is more accurate and more clear.

**URL of affected page:** https://privacyguides.org/browsers/#mobile-browser-recommendations

**Comment by lx-is** [comment]
I think even this change leaves some confusion. "...tabs, and iCloud tabs are end-to-end encrypted" sounds like a typo since it doesn't specify _tabs_ as _tab groups_.

Here's how I would phrase it:
 
"The synchronization of some data via iCloud is [not](https://support.apple.com/en-us/HT202303) end-to-end encrypted. While synchronization of Safari History, Tab Groups, and iCloud Tabs are end-to-end encrypted; bookmarks are only encrypted in transit and stored in an encrypted format. As bookmarks are not end-to-end encrypted, Apple may be able to decrypt and access them."
