### ISSUE TITLE
Firefox settings

### ISSUE THREAD

**Issue by Lostname777** [privacyguides/privacyguides.org#809]
### Discussed in https://github.com/privacyguides/privacyguides.org/discussions/807

<div type='discussions-op-text'>

<sup>Originally posted by **Lostname777** March 28, 2022</sup>
Under the browser recommendations, on the firefox card. You have mentioned "Delete cookies and site data when Firefox is closed" to sanitize on close. But are you aware that this doesn't clear website cache? That has to be done from clear history section.
Shouldn't that be added too in your website? And what about clearing browsing history, downloads and all that stuff. Shouldn't that be recommended too?</div>

**Comment by dngray** [comment]
Browsing history, is something you can decide to do or not. The reason for clearing cookie persistent data/cache on exist is to clear possible tracking data.

A site appearing in your history will not have any data, (so that can't be used to track later visits) etc. Of course if you want to clear that too, by all means do so, but we think most users probably do not.

**Comment by Lostname777** [comment]
Yeah that's fine. But what about the first point. That option **doesn't** clear cache. You need to enable clearing cache **on exit** from **History** tab. Ref. https://support.mozilla.org/en-US/kb/how-clear-firefox-cache

**Comment by mfwmyfacewhen** [comment]
So I just tested it and yeah it doesn't clear your cache completely, however if you're in private browsing mode it clears everything except for some Mozilla entries which are put there every time you start the browser up anyway. I don't think it's necessary to edit the site.

**Comment by mfwmyfacewhen** [comment]
Seems like it's just some weirdness with the Firefox package in some distros. Works fine in the flatpak.
