### ISSUE TITLE
Re-arrange some of the DNS page content

### ISSUE THREAD

**Issue by dngray** [privacyguides/privacyguides.org#834]
## Description

**URL of affected page:** /dns

One of the comments in https://reddit.com/r/PrivacyGuides/comments/tsujrt/new_encrypted_dns_page/i2ubfny/ suggested re-arranging the page so the tutorial stuff is off by itself.

I think this is a good idea, and now we're on mkdocs that should be a lot easier to do.

Might expand it with a bit about testing DNSSEC etc too while I am at it.

**Comment by D0T1X** [comment]
From what i read i understand that the current plan is to reshuffle the content on the same page. However i feel like that, now that Privacyguides is on Mkdocs the DNS explainer is best moved over to the "Privacy introduction" section.
Keeping the recommendations and explaining separate will make it a lot cleaner and easier to read. Maybe for ease of use there could be an backlink between the respective pages so that a user can easily navigate between the two.
Just my two cents, Thanks for your consideration.
I'd be happy to help and spend some time on that, but i'll have to first figure out how mkdocs creates pages.

**Comment by dngray** [comment]
> From what i read i understand that the current plan is to reshuffle the content on the same page. 

> Keeping the recommendations and explaining separate will make it a lot cleaner and easier to read. Maybe for ease of use there could be an backlink between the respective pages so that a user can easily navigate between the two.

Nah, i was thinking like a Encrypted DNS tutorial page, where anything related verifying our claims resides. That allows us to be more assertive with the DNS page and backlink as you say.

> I'd be happy to help and spend some time on that, but i'll have to first figure out how mkdocs creates pages.

oh it's dead simple https://github.com/privacyguides/privacyguides.org/commit/66d85fcfb0a1a90a5954d0fd961ea611f70ef172


In general, though, [this thread](https://old.reddit.com/r/PrivacyGuides/comments/thnjjf/privacyguidesorg_considered_harmful/) had this link which I think has very good advice for us.

https://www.gov.uk/guidance/content-design/writing-for-gov-uk
