### ISSUE TITLE
replace youtube video

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [privacyguides/privacyguides.org#974]
## Description
If u want to let the user play a video in the browser then i suggest u replace the yt video to a privacy respecting platform such as invidious or piped

**URL of affected page:**
https://www.privacyguides.org/security/multi-factor-authentication/#fido2-u2f
https://www.privacyguides.org/linux-desktop/#release-cycle
https://www.privacyguides.org/linux-desktop/#traditional-vs-atomic-updates

**Comment by elitejake** [comment]
As @dngray [mentioned](https://github.com/privacyguides/privacyguides.org/pull/491#discussion_r777101913), using a single Invidious/Piped instance is unreliable because they tend to go down.

Users are better off using userscripts or extensions like [LibRedirect](https://github.com/libredirect/libredirect/) which allows them to pick their own instances.
